# site name
prefixName: ğŸ¦‹
siteName: æ–­æ¡¥ã®çƒŸé›¨
# favicon and site master avatar
favicon: /images/favicon.ico
avatar: /img/custom/avatar.jpg
url: https://zfq0620.github.io
description: ä¸€ä¸‡å¹´å¤ªä¹…ä¹‹äº‰æœå¤•ï¼
cdn: https://cdn.jsdelivr.net/gh/zfq0620/cdn@v1.1
pjax: 1
# 1å¼€å¯
mathjax: 0

notice: æ¬¢è¿æ¥åˆ°æ–­æ¡¥çƒŸé›¨çš„åšå®¢
lazyloadImg: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/loader/orange.progress-bar-stripe-loader.svg

menus:
  é¦–é¡µ: { path: /, fa: fa-fort-awesome faa-shake }
  
  å½’æ¡£: { path: /archives, fa: fa-archive faa-shake, submenus: {  
    æŠ€æœ¯: {path: /categories/æŠ€æœ¯/, fa: fa-code },
    ç”Ÿæ´»: {path: /categories/ç”Ÿæ´»/, fa: fa-file-text-o }, 
    èµ„æº: {path: /categories/èµ„æº/, fa: fa-cloud-download }, 
    éšæƒ³: {path: /categories/éšæƒ³/, fa: fa-commenting-o },
    è½¬è½½: {path: /categories/è½¬è½½/, fa: fa-book }
  } }
  
  å­¦ä¹ : { path: /archives, fa: fa-graduation-cap faa-wrench , submenus: { 
    å‰ç«¯: {path: /tags/å‰ç«¯/, fa: fa-television},
    Cè¯­è¨€: {path: /tags/Cè¯­è¨€/, fa: fa-edit}, 
    åµŒå…¥å¼: {path: /tags/åµŒå…¥å¼/, fa: fa-microchip},
    ç‰©è”ç½‘: {path: /tags/ç‰©è”ç½‘/, fa: fa-bank}
  } }
  
  æ¸…å•: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: { 
    ä¹¦å•: {path: /tags/æ‚¦è¯»/, fa: fa-th-list faa-bounce }, 
    ç•ªç»„: {path: /bangumi/, fa: fa-film faa-vertical }, 
    æ­Œå•: {path: /music/, fa: fa-headphones },
    å›¾é›†: {path: /tags/å›¾é›†/, fa: fa-photo }
  } }
  
  ç•™è¨€æ¿: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  å‹äººå¸: { path: /links/, fa: fa-link faa-shake }
  èµèµ: { path: /donate/, fa: fa-heart faa-pulse }
  å…³äº: {path: /about/, fa: fa-vcard faa-tada}
  RSS: { path: /atom.xml, fa: fa-rss faa-pulse }

  


# Home page sort type: -1: newer firstï¼Œ1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# èƒŒæ™¯å›¾ç‰‡ æ›´å¥½çš„ä¿®æ”¹
bg:
  - https://cdn.jsdelivr.net/gh/yremp/cdn@2.1.5/img/cover/(1).jpg.webp
  - https://cdn.jsdelivr.net/gh/yremp/cdn@2.1.5/img/cover/(2).jpg.webp
  - https://cdn.jsdelivr.net/gh/yremp/cdn@2.1.5/img/cover/(3).jpg.webp
  - https://cdn.jsdelivr.net/gh/yremp/cdn@2.1.5/img/cover/(4).jpg.webp
  - https://cdn.jsdelivr.net/gh/yremp/cdn@2.1.5/img/cover/(5).jpg.webp
  - https://cdn.jsdelivr.net/gh/yremp/cdn@2.1.5/img/cover/(6).jpg.webp
  - https://cdn.jsdelivr.net/gh/yremp/cdn@2.1.5/img/cover/(8).jpg.webp

# èƒŒæ™¯å›¾ç‰‡æ ·å¼ ç©º åŸå›¾æ•ˆæœ filter-dim é˜´å½± filter-grid æ¨ªæ¡ filter-dot ç‚¹ç‚¹
bgclass: filter-dot

# startdash url, title, desc img
startdash: 
  - {url: /theme-sakura/, title: Sakura, desc: æœ¬ç«™ hexo ä¸»é¢˜, img: /img/startdash/sakura.png}
  - {url: https://space.bilibili.com/483624233, title: Bilibili, desc: åšä¸»çš„bç«™è§†é¢‘, img: /img/startdash/bilibili.jpg}
  - {url: https://me.csdn.net/weixin_45631738, title: æ–­æ¡¥çƒŸé›¨çš„CSDN, desc: æŠ€æœ¯æœåŠ¡, img: /img/startdash/wangshiwu.jpg}



# your site build time or founded date
siteBuildingTime: 02/28/2020

#social  url, img PCç«¯é…ç½®
social:
  github: {url: https://gitee.com/zfq0620, img: /img/social/github.png}
  sina: {url: https://gitee.com/zfq0620, img: /img/social/sina.png}
  wangyiyun: {url: https://gitee.com/zfq0620, img: /img/social/wangyiyun.png}
  zhihu: {url: https://www.zhihu.com/people/zfq0620, img: /img/social/zhihu.png}
  email: {url: https://gitee.com/zfq0620, img: /img/social/email.svg}
  wechat: {url: /#, qrcode: /img/custom/weixing.png, img: /img/social/wechat.png}

#social  url, img ç§»åŠ¨ç«¯é…ç½®
msocial:
  github: {url: https://gitee.com/zfq0620, fa: fa-github, color: 333}
  weibo: {url: https://weibo.com/u/6381711951/home?leftnav=1, fa: fa-weibo, color: dd4b39}
  qq: {url: https://wpa.qq.com/msgrd?v=3&uin=18391763855&site=qq&menu=yes, fa: fa-qq, color: 25c6fe}

donate:
  paypal:  https://cdn.jsdelivr.net/gh/zfq0620/cdn@v1.1
  alipay: /img/custom/alipay.jpg
  wechat: /img/custom/wechat.png
  wechatSQ: /img/custom/weixing.png

# è§†é¢‘åœ°å€ä¸ºhttps://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4ï¼Œé…ç½®å¦‚ä¸‹
movies:
  url: https://cdn.jsdelivr.net/gh/honjun/hojun@1.2
  # å¤šä¸ªè§†é¢‘ç”¨é€—å·éš”å¼€ï¼Œéšæœºè·å–ã€‚æ”¯æŒçš„æ ¼å¼ç›®å‰å·²çŸ¥MP4,Flvã€‚å…¶ä»–çš„å¯ä»¥è¯•ä¸‹ï¼Œä¸ä¿è¯æœ‰ç”¨
  name: Unbroken.mp4

aplayer: 
  id: 4887733040
  server: netease
  type: playlist
  fixed: true
  autoplay: false
  loop: all
  order: random
  preload: none
  volume: 0.7
  mutex: true

# Valine
valine: true
v_appId: GyC3NzMvd0hT9Yyd2hYIC0MN-gzGzoHsz
v_appKey: mgOpfzbkHYqU92CV4IDlAUHQ

# Online contact ##åœ¨çº¿èŠå¤©
daovoice: true
daovoice_app_id: f07007f7 ##è¿™é‡Œæ›¿æ¢æˆä½ DaoVoiceä¸Šçš„appid

#2dæ¿å¨˜
live2d:
  enable: true

# Local search æœç´¢
local_search:
  enable: true


  